// Frank's commands, declared so Tauri generates `allow-<command>`
// permissions for them (permissions/autogenerated/, referenced in
// capabilities/default.json) -- the desktop app's build.rs shape, for the
// desktop app's reason. TWO since job 26b (6 Sep): `sync_discover`, the
// Bonjour browse the Transfer tab's Sync button asks for on a phone, and
// `google_sign_in`, which opens Google's consent page in the SYSTEM browser
// (Google refuses it in a web view) and refuses any other address.
// THREE since job 8b (6 Sep): `audio_session_start`, which takes the
// AVAudioSession the moment the reader first plays -- the page can see a
// `play` event and an app cannot, and an app can hold an audio session and
// a page cannot, so the one crosses to the other here.
// SEVEN since G-PULL (11 Sep): `book_put`, `book_meta`, `book_list` and
// `book_remove`, the door a Sync pull stores a book through -- the Cache API
// refuses `frank://`, so a book goes to `<app data>/books/` and the scheme
// handler serves it back at `frank://localhost/books/<slug>/...` (lib.rs,
// "the books").
// Everything else the shell does it does over frank:// and fetch.
fn main() {
    // ios/FrankAudio.m -> the two C symbols `lib.rs` declares under
    // cfg(target_os = "ios"). Compiled here, for iOS targets only, because
    // Xcode never sees this file (it is the crate's, not the project's), and a
    // declared-but-undefined symbol is a link error twenty minutes into a
    // phone build -- which is how it was found at 14:24 on 6 Sep.
    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    if target_os == "ios" {
        println!("cargo:rerun-if-changed=ios/FrankAudio.m");
        cc::Build::new()
            .file("ios/FrankAudio.m")
            .flag("-fobjc-arc")
            .flag("-fmodules")
            .compile("frankaudio");
        // ios/FrankWebView.m -> `frank_webview_fill`, the black bar (job 2,
        // 6 Sep). ITS OWN ARCHIVE and not a second `.file()` on the build
        // above: `compile()` names the archive, and one archive called
        // `frankaudio` holding the webview fix is the kind of lie that costs
        // an hour the next time a symbol goes missing.
        println!("cargo:rerun-if-changed=ios/FrankWebView.m");
        cc::Build::new()
            .file("ios/FrankWebView.m")
            .flag("-fobjc-arc")
            .flag("-fmodules")
            .compile("frankwebview");
        // ios/FrankSearch.m -> `frank_search_present`, the search sheet (job
        // 13, 6 Sep): SFSafariViewController over the app, so "Search the web"
        // never throws the reader away. Its own archive, for the reason above.
        // `search.rs` is its only caller and holds the whole of the why.
        println!("cargo:rerun-if-changed=ios/FrankSearch.m");
        cc::Build::new()
            .file("ios/FrankSearch.m")
            .flag("-fobjc-arc")
            .flag("-fmodules")
            .compile("franksearch");
        // ios/FrankInbox.m -> `frank_inbox_documents` and `frank_inbox_group`,
        // the two roots an incoming share can land in (C2/K8, 13 Sep). Its own
        // archive, for the reason above. Neither path is computable in Rust --
        // a container is a per-install UUID -- and the group call answering nil
        // is the MEASUREMENT of whether this build's team can carry the App
        // Group entitlement at all. `src/inbox.rs` is its only caller and holds
        // the whole of the why. No framework beyond Foundation.
        // ios/FrankLookup.m -> `frank_lookup_present`, Apple's own Look Up
        // panel for one word, as a half sheet over the reader (G-LOOKUP2,
        // 13 Sep). Its own archive, for the reason above. `src/lookup.rs` is
        // its only caller and holds the whole of the why -- including why
        // `dictionaryHasDefinitionForTerm:` is NOT in it (31-95 ms a word).
        // No framework beyond Foundation and UIKit, both already named below.
        println!("cargo:rerun-if-changed=ios/FrankLookup.m");
        cc::Build::new()
            .file("ios/FrankLookup.m")
            .flag("-fobjc-arc")
            .flag("-fmodules")
            .compile("franklookup");
        println!("cargo:rerun-if-changed=ios/FrankInbox.m");
        cc::Build::new()
            .file("ios/FrankInbox.m")
            .flag("-fobjc-arc")
            .flag("-fmodules")
            .compile("frankinbox");
        // ios/FrankSpeech.m -> the native voice (D1(b), 13 Sep):
        // `frank_speech_init`, `_speak`, `_cancel`, `_pause`, `_resume`,
        // `_speaking`, `_voices`. Its own archive, for the reason above.
        // `src/speech.rs` is its only caller and holds the whole of the why --
        // above all why `speak` takes a BATCH: a queued AVSpeechUtterance goes
        // on speaking with this webview's JavaScript suspended, and a
        // sentence-at-a-time reader stops at the lock screen. No framework
        // beyond Foundation and AVFoundation, and AVFoundation has been named
        // below and in `gen/apple/project.yml` since FrankAudio.m -- so this
        // file adds no `sdk:` line to that spec, which is the link-time trap
        // job 8b wrote down.
        println!("cargo:rerun-if-changed=ios/FrankSpeech.m");
        cc::Build::new()
            .file("ios/FrankSpeech.m")
            .flag("-fobjc-arc")
            .flag("-fmodules")
            .compile("frankspeech");
        // Said here for the record and for a non-Xcode link; the build that
        // matters is Xcode's, and it is `gen/apple/project.yml`'s
        // `dependencies:` that actually names these -- a `staticlib` crate
        // never runs a linker, so nothing on this line reaches one.
        println!("cargo:rustc-link-lib=framework=AVFoundation");
        println!("cargo:rustc-link-lib=framework=Foundation");
        println!("cargo:rustc-link-lib=framework=UIKit");
        println!("cargo:rustc-link-lib=framework=SafariServices");
    }
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(
            tauri_build::AppManifest::new().commands(&[
                "sync_discover",
                "google_sign_in",
                "audio_session_start",
                "book_put",
                "book_meta",
                "book_list",
                "book_remove",
                "sync_start",
                "sync_status",
                "sync_stop",
                // the language packs (G-LANG, 11 Sep): src/dict.rs
                "dict_langs",
                "dict_lookup",
                "dict_remove",
                // Apple's Look Up panel (G-LOOKUP2, 13 Sep): src/lookup.rs.
                // TWO, and no per-word `lookup_has` -- that Bool is 31-95 ms.
                "lookup_apple",
                "lookup_apple_offered",
                // the inbox (C2/K8, 13 Sep): src/inbox.rs, read-only
                "inbox_list",
                // ...and (G-INBOX, 13 Sep) the two that make it finishable:
                // one item up to the paired Studio's own `POST /upload`, which
                // parses it, and the item off this phone once it is there.
                "inbox_send",
                "inbox_drop",
                // the native voice (D1(b), 13 Sep): src/speech.rs. SEVEN, and
                // the batch is the point -- `speech_speak` is handed the rest
                // of the chapter so the reading survives the lock screen.
                "speech_available",
                "speech_voices",
                "speech_speak",
                "speech_stop",
                "speech_pause",
                "speech_resume",
                "speech_speaking",
            ]),
        ),
    )
    .expect("tauri_build");
}
