// Frank's commands, declared so Tauri generates `allow-<command>`
// permissions for them (permissions/autogenerated/, referenced in
// capabilities/default.json) -- the desktop app's build.rs shape, for the
// desktop app's reason. ONE command since job 26 (6 Sep): `sync_discover`,
// the Bonjour browse the Transfer tab's Sync button asks for on a phone.
// Everything else the shell does it does over frank:// and fetch.
fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(&["sync_discover"])),
    )
    .expect("tauri_build");
}
