#!/usr/bin/env bash
# tools/android.sh -- the Android apk, built and installed, as one command.
#
# `tools/phone.sh` with Android's differences, and they are real ones:
#
#   * no xcodegen. Android's manifest is generated by `tauri android init` and
#     patched afterwards by `tools/android_permissions.py`; there is no
#     project.yml seam and no regeneration step to forget.
#   * --debug is not a convenience. `build.gradle.kts` sets
#     manifestPlaceholders["usesCleartextTraffic"] "false" in defaultConfig and
#     "true" in the debug build type, so a RELEASE apk cannot reach a
#     plain-http Studio on the LAN and carries no web inspector.
#   * the apk's path is printed, not fixed. This finds it rather than assuming
#     `outputs/apk/universal/debug/`, because --split-per-abi and a future
#     Gradle both move it.
#
# The daily Android loop is not this file either -- it is `npx tauri android
# dev`, which needs no network at all: Tauri runs `adb reverse tcp:P tcp:P`, so
# localhost on the device IS the Mac. See PHONE.md §5.
#
# usage:  tools/android.sh [--shell] [--ttstv PATH] [--device SERIAL] [--no-install]
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GEN="$REPO/src-tauri/gen/android"

WITH_SHELL=0
TTSTV="${TTSTV:-$HOME/Documents/RUNNERS/TTSTV/TTSTV}"
DEVICE=""
INSTALL=1
while [ $# -gt 0 ]; do
  case "$1" in
    --shell)      WITH_SHELL=1; shift ;;
    --ttstv)      TTSTV="$2"; shift 2 ;;
    --device)     DEVICE="$2"; shift 2 ;;
    --no-install) INSTALL=0; shift ;;
    -h|--help)    sed -n '2,22p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *)            echo "android.sh: unknown argument $1 (try --help)" >&2; exit 2 ;;
  esac
done

say() { printf '\n\033[1m== %s\033[0m\n' "$*"; }

export PATH="$HOME/.cargo/bin:$PATH"
# Android's Gradle wants the JDK Android Studio ships. Tauri substitutes it only
# when JAVA_HOME is UNSET (tauri-cli `ensure_java`), so a JDK 25 exported in a
# shell profile wins and Gradle refuses. Set it here only if it is not already
# pointing at a JBR -- never overriding a deliberate choice silently.
STUDIO_JBR="/Applications/Android Studio.app/Contents/jbr/Contents/Home"
if [ -d "$STUDIO_JBR" ] && [ "${JAVA_HOME:-}" != "$STUDIO_JBR" ]; then
  if [ -n "${JAVA_HOME:-}" ]; then
    echo "android.sh: JAVA_HOME is $JAVA_HOME; using Android Studio's JBR instead (PHONE.md §5.0)"
  fi
  export JAVA_HOME="$STUDIO_JBR"
fi
command -v cargo >/dev/null || { echo "android.sh: no cargo on PATH (rustup?)" >&2; exit 1; }
command -v adb   >/dev/null || { echo "android.sh: no adb on PATH -- \$ANDROID_HOME/platform-tools" >&2; exit 1; }
[ -d "$GEN" ] || { echo "android.sh: no $GEN -- run \`npx tauri android init\` first (PHONE.md §5.1)" >&2; exit 1; }

if [ "$WITH_SHELL" = 1 ]; then
  say "1/3  import the shell from $TTSTV"
  python3 "$REPO/tools/import_shell.py" --ttstv "$TTSTV"
else
  say "1/3  shell: not re-imported (pass --shell to take a new one from TTSTV)"
fi

# The manifest is regenerated by `init`, so the permission has to be put back.
# Idempotent: it says so and changes nothing when it is already there.
say "2/3  RECORD_AUDIO into the generated manifest"
python3 "$REPO/tools/android_permissions.py"

say "3/3  tauri android build --apk --debug"
( cd "$REPO" && npm run --silent -- tauri android build --apk --debug )

APK="$(find "$GEN/app/build/outputs/apk" -name '*debug*.apk' -type f 2>/dev/null \
       | xargs -r ls -t 2>/dev/null | head -1 || true)"
[ -n "$APK" ] || { echo "android.sh: the build produced no debug .apk under $GEN/app/build/outputs/apk" >&2; exit 1; }
printf 'built: %s (%s)\n' "$APK" "$(du -h "$APK" | cut -f1)"

if [ "$INSTALL" = 0 ]; then
  say "install: skipped (--no-install)"
  exit 0
fi

if [ -z "$DEVICE" ]; then
  DEVICE="$(adb devices | awk 'NR>1 && $2=="device" {print $1}')"
  n="$(printf '%s\n' "$DEVICE" | grep -c . || true)"
  if [ "$n" -eq 0 ]; then
    echo "android.sh: no device. Start the AVD, or plug a phone in with USB debugging on." >&2
    echo "            adb devices" >&2
    exit 1
  fi
  if [ "$n" -gt 1 ]; then
    echo "android.sh: more than one device -- name the one you mean with --device:" >&2
    adb devices >&2
    exit 1
  fi
fi

say "install onto $DEVICE"
# -r reinstalls over the same signature rather than failing on INSTALL_FAILED_
# ALREADY_EXISTS, which is what a second run always hits.
adb -s "$DEVICE" install -r "$APK"
echo
echo "Open Frank. If the Library is blank or garbled, the log says which:"
echo "  Chrome > chrome://inspect/#devices > inspect  (PHONE.md §5.3)"
