"""Generate the iOS app icons from the Frank mark.

    python3 tools/gen_icons.py --ttstv ~/Documents/RUNNERS/TTSTV/TTSTV

Writes the eighteen PNGs `src-tauri/gen/apple/Assets.xcassets/AppIcon.appiconset/
Contents.json` names, at the exact pixel size each entry asks for. Committed
source, regenerated by hand -- Xcode reads the catalogue as committed and nothing
runs this automatically.

WHY THIS EXISTS AT ALL (7 Sep). `tauri ios init` wrote that catalogue once, from
its own defaults, and **nothing has re-derived it since** -- so the phone was
carrying Tauri's yellow-and-cyan placeholder ring on the home screen while
`src-tauri/icons/` beside it held the correct Frank mark, byte-identical to the
Mac's. That is the trap: `src-tauri/icons/` is `tauri.conf.json`'s DESKTOP bundle
list. iOS does not read it. It reads the asset catalogue, and the asset catalogue
had no generator. `TTSTV/design/icons/mark.html` is the ledger where the empty
row was showing.

This is the third generator beside `TTSTV/desktop/tools/gen_icons.py` (the Mac)
and `TTSTV/reader/tools/gen_icons.py` (the PWA), and it keeps their rules:

* **The masters are TTSTV's**, not vendored here. `Frank/frank-icon.svg` and
  `Frank/frank-mark-dock.svg`, reached by `--ttstv`, the same way
  `tools/import_shell.py` reaches the shell. Two copies of a master is one copy
  too many.
* **`SMALL_UP_TO = 64`**, Osca's 31 Aug split, unchanged: 64 px and below get the
  dock mark (W and B alone), above it the full mark. Five stacked letters plus two
  sideways ones do not survive a 20 px icon.
* **Every size is drawn from the vector at its own size.** Nothing is downsampled
  from a bigger PNG, which is why 20 px is a drawing and not a smear -- and why
  `npx tauri icon` is the wrong tool here: it rasterises a 512 PNG down.
* Same rasteriser ladder: `$SVG_RASTERIZER`, `cairosvg`, `rsvg-convert`, headless
  Chrome. **If none is present it says so and writes nothing**, rather than
  shipping an icon that quietly lost its curves.

THE TWO THINGS iOS NEEDS THAT THE MAC DOES NOT

1. **Full bleed, and the platform does the rounding.** `frank-icon.svg` draws its
   own rounded tile inset 6 %, with transparency outside it. On iOS that lands as
   a rounded tile inside iOS's own rounded mask, floating in a transparent gap --
   wrong twice. So each master gets an opaque `#fffbf9` field over the whole
   square, with the art on top **at its own size** (`IOS_SCALE = 1.0`).

   **Not at the maskable's 0.8**, and the number says why. `frank-icon-maskable.svg`
   insets the art to 80 % because a *maskable* icon may be cropped to a CIRCLE, and
   Android does. iOS does not: it rounds the corners at 22.37 % and takes
   everything else. Measured as ink extent across the square:

       the Mac's approved 128x128.png (full mark)   76.6 % x 89.1 %
       this, full bleed at scale 1.00               76.6 % x 89.1 %   <- the same
       this, at the maskable's 0.80                 60.2 % x 71.9 %
       the PWA's icon-512.png, for comparison       60.5 % x 70.7 %

   At 0.8 the phone would carry the Android-sized mark; at 1.0 it carries the one
   Osca approved for the Dock. And because the art is inset 6 % already while
   iOS's mask has no inset, **nothing of the mark is cropped either way** -- the
   corners iOS takes are bare field.

   **Both halves of that are proved, not asserted:**
   `--check-derivation` shows the wrap mechanism is Osca's own, by applying it at
   0.8 to `frank-icon.svg` and rendering against the real
   `frank-icon-maskable.svg`; `--check-parity` shows the output is the approved
   Mac icon, by compositing `desktop/src-tauri/icons/128x128.png` and `32x32.png`
   onto the field and diffing them against what this writes.
2. **No alpha channel.** An app icon with alpha is rejected at submission. Every
   PNG is flattened to RGB over the field colour and written with no alpha band;
   `--verify` re-opens each file and fails if a mode other than RGB comes back.

usage:
    python3 tools/gen_icons.py --ttstv <path>                     write the eighteen
    python3 tools/gen_icons.py --ttstv <path> --verify            write, then re-open each
    python3 tools/gen_icons.py --ttstv <path> --check-derivation  prove the wrap; write nothing
    python3 tools/gen_icons.py --ttstv <path> --check-parity      prove it is the Mac's mark
    python3 tools/gen_icons.py --ttstv <path> --check-only        check what is on disk
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import struct
import subprocess
import sys
import tempfile
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
APPICON = ROOT / "src-tauri" / "gen" / "apple" / "Assets.xcassets" / "AppIcon.appiconset"

SMALL_UP_TO = 64            # 64 and below: the dock mark. Osca, 31 Aug.
FIELD = "#fffbf9"           # the mark's own field -- Frank/ICONOGRAPHY.md §2
IOS_SCALE = 1.0             # the art at its own size -- see the docstring, §1
MASKABLE_SCALE = 0.8        # Android's circle-crop inset. Used ONLY by
                            # --check-derivation, to prove the wrap is Osca's.

CHROMES = [
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/Applications/Chromium.app/Contents/MacOS/Chromium",
    "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
    "/opt/pw-browsers/chromium-1194/chrome-linux/chrome",
    "chromium",
    "google-chrome",
]


# --------------------------------------------------------------------------
def _ttstv(path: Path) -> Path:
    """The same check `tools/import_shell.py` makes, against what THIS reads."""
    root = path.expanduser().resolve()
    if not (root / "Frank" / "frank-icon.svg").is_file():
        raise SystemExit(
            f"{root} is not a TTSTV checkout: no Frank/frank-icon.svg, which is "
            f"the master this generator draws every size from"
        )
    return root


def full_bleed(svg_text: str, scale: float = IOS_SCALE) -> str:
    """An opaque field over the whole 1024 square, the master's body on top.

    `scale` 1.0 leaves the art at its own size (what iOS ships); 0.8 reproduces
    Frank/frank-icon-maskable.svg exactly, which is how --check-derivation proves
    this function is Osca's wrap and not one invented here.

    The <defs> stay OUTSIDE the group: a clipPath inside a scaled group would be
    scaled twice, and the letters would be cut in the wrong place.
    """
    m = re.search(r"</defs>", svg_text)
    if not m:
        raise SystemExit("master has no </defs>: its shape is not what this expects")
    head, body = svg_text[:m.end()], svg_text[m.end():]
    body = re.sub(r"</svg>\s*$", "", body)
    off = 1024 * (1 - scale) / 2
    return (head
            + f'\n<rect width="1024" height="1024" fill="{FIELD}"/>\n'
            + f'<g transform="translate({off} {off}) scale({scale})">'
            + body + "</g>\n</svg>\n")


def _rasterise(svg: Path, png: Path, px: int) -> bool:
    """Render `svg` to a px-by-px `png`.  False if no rung of the ladder can."""
    cmd = os.environ.get("SVG_RASTERIZER")
    if cmd:
        subprocess.run([*cmd.split(), str(svg), str(png), str(px)], check=True)
        return True

    try:
        import cairosvg  # type: ignore
    except ImportError:
        pass
    else:
        cairosvg.svg2png(url=str(svg), write_to=str(png),
                         output_width=px, output_height=px)
        return True

    rsvg = shutil.which("rsvg-convert")
    if rsvg:
        subprocess.run([rsvg, "-w", str(px), "-h", str(px), "-o", str(png), str(svg)],
                       check=True)
        return True

    for c in CHROMES:
        exe = c if Path(c).exists() else shutil.which(c)
        if not exe:
            continue
        with tempfile.TemporaryDirectory() as tmp:
            page = Path(tmp) / "icon.html"
            page.write_text(
                "<style>html,body{margin:0;padding:0;background:transparent}"
                f"img{{display:block;width:{px}px;height:{px}px}}</style>"
                f'<img src="{svg.as_uri()}">')
            subprocess.run([exe, "--headless=new", "--disable-gpu", "--no-sandbox",
                            "--hide-scrollbars", "--force-device-scale-factor=1",
                            "--default-background-color=00000000",
                            f"--window-size={px},{px}", f"--screenshot={png}",
                            str(page.as_uri())], check=True, capture_output=True)
        return png.exists()
    return False


def _flatten(png: Path) -> None:
    """RGBA -> RGB over the field.  An app icon with alpha is rejected."""
    from PIL import Image
    im = Image.open(png)
    if im.mode == "RGB":
        im.close()
        return
    im = im.convert("RGBA")
    bg = Image.new("RGBA", im.size, FIELD)
    out = Image.alpha_composite(bg, im).convert("RGB")
    im.close()
    out.save(png, "PNG", optimize=True)
    out.close()


# --------------------------------------------------------------------------
def wanted() -> dict:
    """filename -> pixel size, read out of Contents.json.

    The catalogue is the authority on the set, not a list retyped here: Apple's
    required sizes are whatever Xcode wrote, and a size this script invented
    would be a size Xcode ignores.
    """
    spec = json.loads((APPICON / "Contents.json").read_text())
    out = {}
    for e in spec["images"]:
        pt = float(e["size"].split("x")[0])
        px = int(round(pt * float(e["scale"].rstrip("x"))))
        out[e["filename"]] = px
    return out


# --------------------------------------------------------------------------
# READING A PNG WITH NO THIRD-PARTY ANYTHING
#
# `tools/prebuild.py` calls `icon_problems()` on every build and every dev run,
# so the guard has to hold on a machine where Pillow was never installed -- a
# guard that skips itself when an import fails is the shape of bug this whole
# lane exists to fix.  Pillow is still needed to WRITE (the alpha flatten) and
# to run the two comparison proofs; it is not needed to CHECK.
#
# This reads enough of PNG for the question being asked: 8-bit, non-interlaced,
# colour type 2 (RGB) or 6 (RGBA).  That is everything this generator writes and
# everything `tauri ios init` wrote before it.  Anything else raises rather than
# guessing, and a raise is a build failure, not a shrug.
# --------------------------------------------------------------------------
PNG_MAGIC = b"\x89PNG\r\n\x1a\n"


def _png_read(path: Path):
    """-> (width, height, channels, pixel bytes).  Standard library only."""
    raw = path.read_bytes()
    if raw[:8] != PNG_MAGIC:
        raise ValueError("not a PNG")
    pos, idat, hdr = 8, [], None
    while pos + 8 <= len(raw):
        (ln,) = struct.unpack(">I", raw[pos:pos + 4])
        typ = raw[pos + 4:pos + 8]
        body = raw[pos + 8:pos + 8 + ln]
        pos += 12 + ln                       # 4 length + 4 type + body + 4 CRC
        if typ == b"IHDR":
            hdr = struct.unpack(">IIBBBBB", body)
        elif typ == b"IDAT":
            idat.append(body)
        elif typ == b"IEND":
            break
    if hdr is None:
        raise ValueError("no IHDR")
    w, h, depth, ctype, _comp, _filt, interlace = hdr
    if depth != 8 or interlace != 0 or ctype not in (2, 6):
        raise ValueError(f"unsupported PNG: {depth}-bit, colour type {ctype}, "
                         f"interlace {interlace}")

    ch = 3 if ctype == 2 else 4
    data = zlib.decompress(b"".join(idat))
    stride = w * ch
    out = bytearray(h * stride)
    prev = bytes(stride)
    p = 0
    for y in range(h):
        f = data[p]; p += 1
        line = bytearray(data[p:p + stride]); p += stride
        if f == 0:
            pass
        elif f == 1:                                            # Sub
            for i in range(ch, stride):
                line[i] = (line[i] + line[i - ch]) & 0xFF
        elif f == 2:                                            # Up
            for i in range(stride):
                line[i] = (line[i] + prev[i]) & 0xFF
        elif f == 3:                                            # Average
            for i in range(stride):
                a = line[i - ch] if i >= ch else 0
                line[i] = (line[i] + ((a + prev[i]) >> 1)) & 0xFF
        elif f == 4:                                            # Paeth
            for i in range(stride):
                a = line[i - ch] if i >= ch else 0
                b = prev[i]
                c = prev[i - ch] if i >= ch else 0
                pa, pb, pc = abs(b - c), abs(a - c), abs(a + b - 2 * c)
                pr = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
                line[i] = (line[i] + pr) & 0xFF
        else:
            raise ValueError(f"unknown PNG filter {f} on row {y}")
        out[y * stride:(y + 1) * stride] = line
        prev = bytes(line)
    return w, h, ch, bytes(out)


def _placeholder_pixels(px: bytes, ch: int) -> int:
    """Count saturated non-red pixels.

    Tauri's placeholder is a yellow ring and a cyan one.  The only saturated
    colour anywhere in the Frank mark is #c8102e, so a saturated pixel that is
    not red cannot be Frank's -- which makes this a test the placeholder cannot
    pass and the mark cannot fail.
    """
    hits = 0
    for i in range(0, len(px), ch):
        r, g, b = px[i], px[i + 1], px[i + 2]
        if max(r, g, b) - min(r, g, b) < 60:
            continue                             # near-grey: the field or the ink
        if r > g + 40 and r > b + 40:
            continue                             # the mark's own red
        hits += 1
    return hits


def inspect(files: dict | None = None):
    """Re-open every file the catalogue names.  -> (rows, problems)

    rows: (name, w, h, "RGB"/"RGBA"/"?", placeholder pixels, ok)
    Both `check()` (which prints) and `icon_problems()` (which does not) read
    this, so there is one definition of what "correct" means.
    """
    files = files or wanted()
    on_disk = {p.name for p in APPICON.glob("*.png")}
    rows, problems = [], []

    for name in sorted(set(files) - on_disk):
        problems.append(f"{name}: named by Contents.json, absent from the catalogue")
    for name in sorted(on_disk - set(files)):
        problems.append(f"{name}: in the catalogue, named by nothing in Contents.json")

    for name, px in sorted(files.items(), key=lambda kv: kv[1]):
        p = APPICON / name
        if not p.exists():
            continue
        try:
            w, h, ch, pixels = _png_read(p)
        except (ValueError, zlib.error) as e:
            rows.append((name, 0, 0, "?", -1, False))
            problems.append(f"{name}: unreadable -- {e}")
            continue
        mode = "RGB" if ch == 3 else "RGBA"
        hits = _placeholder_pixels(pixels, ch)
        ok = (w == px and h == px and ch == 3 and hits == 0)
        rows.append((name, w, h, mode, hits, ok))
        if w != px or h != px:
            problems.append(f"{name}: {w}x{h}, Contents.json says {px}x{px}")
        if ch != 3:
            problems.append(f"{name}: {mode} -- an app icon may not carry an alpha channel")
        if hits:
            problems.append(f"{name}: {hits} saturated non-red pixels -- "
                            f"this is not the Frank mark")
    return rows, problems


def icon_problems() -> list:
    """Every reason the catalogue is not the Frank mark, as lines.  Empty is good.

    This is `tools/prebuild.py`'s entry point.  It prints nothing, imports
    nothing outside the standard library, and is the whole of the build guard.
    """
    try:
        return inspect()[1]
    except FileNotFoundError as e:
        return [f"the app icon catalogue could not be read: {e}"]


def generate(ttstv: Path, verify: bool = False) -> int:
    masters = {
        "dock": (ttstv / "Frank" / "frank-mark-dock.svg").read_text(),
        "full": (ttstv / "Frank" / "frank-icon.svg").read_text(),
    }
    files = wanted()
    sizes = sorted(set(files.values()))
    print(f"{len(files)} files, {len(sizes)} distinct sizes: "
          f"{', '.join(str(s) for s in sizes)}")

    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        wrapped = {}
        for k, text in masters.items():
            p = tmp / f"{k}.svg"
            p.write_text(full_bleed(text))
            wrapped[k] = p

        rendered = {}
        for px in sizes:
            which = "dock" if px <= SMALL_UP_TO else "full"
            png = tmp / f"{px}.png"
            if not _rasterise(wrapped[which], png, px):
                raise SystemExit(
                    "no SVG rasteriser: set $SVG_RASTERIZER, or "
                    "`pip3 install --user cairosvg`, or install rsvg-convert or "
                    "Chrome. Nothing was written.")
            _flatten(png)
            rendered[px] = (png, which)

        APPICON.mkdir(parents=True, exist_ok=True)
        for name, px in sorted(files.items(), key=lambda kv: kv[1]):
            src, which = rendered[px]
            shutil.copyfile(src, APPICON / name)
            print(f"  {name:<32} {px:>4} px  {which}")

    if verify:
        return check(files)
    return 0


def check(files: dict | None = None) -> int:
    """Print the table, then the verdict.  Same rules as `icon_problems()`."""
    files = files or wanted()
    rows, problems = inspect(files)
    for name, w, h, mode, hits, ok in rows:
        size = f"{w}x{h}" if w else "unreadable"
        print(f"  {name:<32} {size:<11} {mode:<5} placeholder-px={hits}  "
              f"{'ok' if ok else 'FAIL'}")
    if problems:
        print("\nFAILED:")
        for b in problems:
            print("  -", b)
        return 1
    print(f"\n{len(files)} files, every one square at its Contents.json size, "
          f"RGB with no alpha, no placeholder colour anywhere.")
    return 0


def check_derivation(ttstv: Path) -> int:
    """Prove `full_bleed` is Osca's wrap and not one invented here.

    Apply it to frank-icon.svg and render against the real
    frank-icon-maskable.svg at 1024. Anything but an exact match means the two
    constants above were read wrong, and every icon this writes is subtly off.
    """
    from PIL import Image, ImageChops
    src = (ttstv / "Frank" / "frank-icon.svg").read_text()
    real = ttstv / "Frank" / "frank-icon-maskable.svg"
    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        (tmp / "derived.svg").write_text(full_bleed(src, MASKABLE_SCALE))
        for n, s in (("derived", tmp / "derived.svg"), ("real", real)):
            if not _rasterise(s, tmp / f"{n}.png", 1024):
                raise SystemExit("no SVG rasteriser; nothing proved and nothing written.")
        a = Image.open(tmp / "derived.png").convert("RGB")
        b = Image.open(tmp / "real.png").convert("RGB")
        raw = ImageChops.difference(a, b).tobytes()
        n = sum(1 for i in range(0, len(raw), 3) if raw[i] or raw[i + 1] or raw[i + 2])
        worst = max(raw) if raw else 0
        total = a.size[0] * a.size[1]
    print(f"derivation vs Frank/frank-icon-maskable.svg at 1024: "
          f"{n} of {total} pixels differ ({100.0 * n / total:.4f} %), "
          f"worst channel delta {worst}")
    if n == 0:
        print("EXACT -- the wrap in this file is the maskable master's own.")
        return 0
    if worst <= 2 and n < total * 0.001:
        print("within antialiasing -- the wrap is the maskable master's own.")
        return 0
    print("DIFFERENT -- do not ship this. The two constants have been read wrong.")
    return 1


def check_parity(ttstv: Path) -> int:
    """Prove what this writes IS the mark Osca approved for the Dock.

    The Mac's icons are the reference of record: they were built from the same
    two masters on 1 Sep, installed, and verified chunk-by-chunk with `iconutil`
    (Frank/ICONOGRAPHY.md §7).  Composite one onto the field -- which is the only
    thing this generator does differently -- and it should equal ours exactly.
    Anything above a rasteriser's rounding means the scale or the master is wrong.
    """
    from PIL import Image, ImageChops
    cases = [
        ("desktop/src-tauri/icons/128x128.png", "Frank/frank-icon.svg", 128, "full"),
        ("desktop/src-tauri/icons/32x32.png", "Frank/frank-mark-dock.svg", 32, "dock"),
    ]
    worst_overall, bad = 0, []
    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        for rel, master, px, which in cases:
            mac_png = ttstv / rel
            if not mac_png.is_file():
                print(f"  {rel}: absent -- skipped")
                continue
            svg = tmp / f"{which}.svg"
            svg.write_text(full_bleed((ttstv / master).read_text()))
            out = tmp / f"{which}.png"
            if not _rasterise(svg, out, px):
                raise SystemExit("no SVG rasteriser; nothing proved and nothing written.")
            mac = Image.open(mac_png).convert("RGBA")
            flat = Image.alpha_composite(Image.new("RGBA", mac.size, FIELD), mac).convert("RGB")
            ours = Image.open(out).convert("RGB")
            raw = ImageChops.difference(flat, ours).tobytes()
            n = sum(1 for i in range(0, len(raw), 3) if raw[i] or raw[i + 1] or raw[i + 2])
            worst = max(raw) if raw else 0
            total = px * px
            worst_overall = max(worst_overall, worst)
            print(f"  {rel} on the field vs this at {px}: {n}/{total} px differ "
                  f"({100.0 * n / total:.3f} %), worst channel delta {worst}")
            mac.close(); flat.close(); ours.close()
            if worst > 2:
                bad.append(f"{rel}: worst delta {worst} -- that is not antialiasing")
    if bad:
        print("\nFAILED:")
        for b in bad:
            print("  -", b)
        return 1
    print(f"\nthe iOS icon IS the Mac's approved mark on an opaque field "
          f"(worst channel delta {worst_overall}, i.e. rasteriser rounding).")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--ttstv", type=Path, default=None,
                    help="path to the TTSTV checkout that holds Frank/. Required for "
                         "everything except --check-only, which reads only this repo -- "
                         "so a build machine with no TTSTV on it can still run the guard.")
    ap.add_argument("--verify", action="store_true",
                    help="after writing, re-open every file and check it")
    ap.add_argument("--check-derivation", action="store_true",
                    help="prove the full-bleed wrap against the maskable master; write nothing")
    ap.add_argument("--check-parity", action="store_true",
                    help="prove the output is the Mac's approved mark; write nothing")
    ap.add_argument("--check-only", action="store_true",
                    help="check what is already on disk; write nothing")
    a = ap.parse_args(argv)
    if a.check_only:
        return check()
    if a.ttstv is None:
        ap.error("--ttstv is required (everything but --check-only reads Frank/)")
    root = _ttstv(a.ttstv)
    if a.check_derivation:
        return check_derivation(root)
    if a.check_parity:
        return check_parity(root)
    return generate(root, verify=a.verify)


if __name__ == "__main__":
    sys.exit(main())
