"""Generate the iOS app icons from the Frank mark.

    python3 tools/gen_icons.py --ttstv ~/Documents/RUNNERS/TTSTV/TTSTV

Writes the eighteen PNGs `src-tauri/gen/apple/Assets.xcassets/AppIcon.appiconset/
Contents.json` names, at the exact pixel size each entry asks for. Committed
source, regenerated by hand -- Xcode reads the catalogue as committed and nothing
runs this automatically.

WHY THIS EXISTS AT ALL (7 Sep). `tauri ios init` wrote that catalogue once, from
its own defaults, and **nothing has re-derived it since** -- so the phone was
carrying Tauri's yellow-and-cyan placeholder ring on the home screen while
`src-tauri/icons/` beside it held the correct Frank mark, byte-identical to the
Mac's. That is the trap: `src-tauri/icons/` is `tauri.conf.json`'s DESKTOP bundle
list. iOS does not read it. It reads the asset catalogue, and the asset catalogue
had no generator. `TTSTV/design/icons/mark.html` is the ledger where the empty
row was showing.

This is the third generator beside `TTSTV/desktop/tools/gen_icons.py` (the Mac)
and `TTSTV/reader/tools/gen_icons.py` (the PWA), and it keeps their rules:

* **The masters are TTSTV's**, not vendored here. `Frank/frank-icon.svg` and
  `Frank/frank-mark-dock.svg`, reached by `--ttstv`, the same way
  `tools/import_shell.py` reaches the shell. Two copies of a master is one copy
  too many.
* **`SMALL_UP_TO = 64`**, Osca's 31 Aug split, unchanged: 64 px and below get the
  dock mark (W and B alone), above it the full mark. Five stacked letters plus two
  sideways ones do not survive a 20 px icon.
* **Every size is drawn from the vector at its own size.** Nothing is downsampled
  from a bigger PNG, which is why 20 px is a drawing and not a smear -- and why
  `npx tauri icon` is the wrong tool here: it rasterises a 512 PNG down.
* Same rasteriser ladder: `$SVG_RASTERIZER`, `cairosvg`, `rsvg-convert`, headless
  Chrome. **If none is present it says so and writes nothing**, rather than
  shipping an icon that quietly lost its curves.

THE TWO THINGS iOS NEEDS THAT THE MAC DOES NOT

1. **Full bleed, and the platform does the rounding.** `frank-icon.svg` draws its
   own rounded tile inset 6 %, with transparency outside it. On iOS that lands as
   a rounded tile inside iOS's own rounded mask, floating in a transparent gap --
   wrong twice. So each master gets an opaque `#fffbf9` field over the whole
   square, with the art on top **at its own size** (`IOS_SCALE = 1.0`).

   **Not at the maskable's 0.8**, and the number says why. `frank-icon-maskable.svg`
   insets the art to 80 % because a *maskable* icon may be cropped to a CIRCLE, and
   Android does. iOS does not: it rounds the corners at 22.37 % and takes
   everything else. Measured as ink extent across the square:

       the Mac's approved 128x128.png (full mark)   76.6 % x 89.1 %
       this, full bleed at scale 1.00               76.6 % x 89.1 %   <- the same
       this, at the maskable's 0.80                 60.2 % x 71.9 %
       the PWA's icon-512.png, for comparison       60.5 % x 70.7 %

   At 0.8 the phone would carry the Android-sized mark; at 1.0 it carries the one
   Osca approved for the Dock. And because the art is inset 6 % already while
   iOS's mask has no inset, **nothing of the mark is cropped either way** -- the
   corners iOS takes are bare field.

   **Both halves of that are proved, not asserted:**
   `--check-derivation` shows the wrap mechanism is Osca's own, by applying it at
   0.8 to `frank-icon.svg` and rendering against the real
   `frank-icon-maskable.svg`; `--check-parity` shows the output is the approved
   Mac icon, by compositing `desktop/src-tauri/icons/128x128.png` and `32x32.png`
   onto the field and diffing them against what this writes.
2. **No alpha channel.** An app icon with alpha is rejected at submission. Every
   PNG is flattened to RGB over the field colour and written with no alpha band;
   `--verify` re-opens each file and fails if a mode other than RGB comes back.

usage:
    python3 tools/gen_icons.py --ttstv <path>                     write the eighteen
    python3 tools/gen_icons.py --ttstv <path> --verify            write, then re-open each
    python3 tools/gen_icons.py --ttstv <path> --check-derivation  prove the wrap; write nothing
    python3 tools/gen_icons.py --ttstv <path> --check-parity      prove it is the Mac's mark
    python3 tools/gen_icons.py --ttstv <path> --check-only        check what is on disk
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
APPICON = ROOT / "src-tauri" / "gen" / "apple" / "Assets.xcassets" / "AppIcon.appiconset"

SMALL_UP_TO = 64            # 64 and below: the dock mark. Osca, 31 Aug.
FIELD = "#fffbf9"           # the mark's own field -- Frank/ICONOGRAPHY.md §2
IOS_SCALE = 1.0             # the art at its own size -- see the docstring, §1
MASKABLE_SCALE = 0.8        # Android's circle-crop inset. Used ONLY by
                            # --check-derivation, to prove the wrap is Osca's.

CHROMES = [
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/Applications/Chromium.app/Contents/MacOS/Chromium",
    "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
    "/opt/pw-browsers/chromium-1194/chrome-linux/chrome",
    "chromium",
    "google-chrome",
]


# --------------------------------------------------------------------------
def _ttstv(path: Path) -> Path:
    """The same check `tools/import_shell.py` makes, against what THIS reads."""
    root = path.expanduser().resolve()
    if not (root / "Frank" / "frank-icon.svg").is_file():
        raise SystemExit(
            f"{root} is not a TTSTV checkout: no Frank/frank-icon.svg, which is "
            f"the master this generator draws every size from"
        )
    return root


def full_bleed(svg_text: str, scale: float = IOS_SCALE) -> str:
    """An opaque field over the whole 1024 square, the master's body on top.

    `scale` 1.0 leaves the art at its own size (what iOS ships); 0.8 reproduces
    Frank/frank-icon-maskable.svg exactly, which is how --check-derivation proves
    this function is Osca's wrap and not one invented here.

    The <defs> stay OUTSIDE the group: a clipPath inside a scaled group would be
    scaled twice, and the letters would be cut in the wrong place.
    """
    m = re.search(r"</defs>", svg_text)
    if not m:
        raise SystemExit("master has no </defs>: its shape is not what this expects")
    head, body = svg_text[:m.end()], svg_text[m.end():]
    body = re.sub(r"</svg>\s*$", "", body)
    off = 1024 * (1 - scale) / 2
    return (head
            + f'\n<rect width="1024" height="1024" fill="{FIELD}"/>\n'
            + f'<g transform="translate({off} {off}) scale({scale})">'
            + body + "</g>\n</svg>\n")


def _rasterise(svg: Path, png: Path, px: int) -> bool:
    """Render `svg` to a px-by-px `png`.  False if no rung of the ladder can."""
    cmd = os.environ.get("SVG_RASTERIZER")
    if cmd:
        subprocess.run([*cmd.split(), str(svg), str(png), str(px)], check=True)
        return True

    try:
        import cairosvg  # type: ignore
    except ImportError:
        pass
    else:
        cairosvg.svg2png(url=str(svg), write_to=str(png),
                         output_width=px, output_height=px)
        return True

    rsvg = shutil.which("rsvg-convert")
    if rsvg:
        subprocess.run([rsvg, "-w", str(px), "-h", str(px), "-o", str(png), str(svg)],
                       check=True)
        return True

    for c in CHROMES:
        exe = c if Path(c).exists() else shutil.which(c)
        if not exe:
            continue
        with tempfile.TemporaryDirectory() as tmp:
            page = Path(tmp) / "icon.html"
            page.write_text(
                "<style>html,body{margin:0;padding:0;background:transparent}"
                f"img{{display:block;width:{px}px;height:{px}px}}</style>"
                f'<img src="{svg.as_uri()}">')
            subprocess.run([exe, "--headless=new", "--disable-gpu", "--no-sandbox",
                            "--hide-scrollbars", "--force-device-scale-factor=1",
                            "--default-background-color=00000000",
                            f"--window-size={px},{px}", f"--screenshot={png}",
                            str(page.as_uri())], check=True, capture_output=True)
        return png.exists()
    return False


def _flatten(png: Path) -> None:
    """RGBA -> RGB over the field.  An app icon with alpha is rejected."""
    from PIL import Image
    im = Image.open(png)
    if im.mode == "RGB":
        im.close()
        return
    im = im.convert("RGBA")
    bg = Image.new("RGBA", im.size, FIELD)
    out = Image.alpha_composite(bg, im).convert("RGB")
    im.close()
    out.save(png, "PNG", optimize=True)
    out.close()


# --------------------------------------------------------------------------
def wanted() -> dict:
    """filename -> pixel size, read out of Contents.json.

    The catalogue is the authority on the set, not a list retyped here: Apple's
    required sizes are whatever Xcode wrote, and a size this script invented
    would be a size Xcode ignores.
    """
    spec = json.loads((APPICON / "Contents.json").read_text())
    out = {}
    for e in spec["images"]:
        pt = float(e["size"].split("x")[0])
        px = int(round(pt * float(e["scale"].rstrip("x"))))
        out[e["filename"]] = px
    return out


def generate(ttstv: Path, verify: bool = False) -> int:
    masters = {
        "dock": (ttstv / "Frank" / "frank-mark-dock.svg").read_text(),
        "full": (ttstv / "Frank" / "frank-icon.svg").read_text(),
    }
    files = wanted()
    sizes = sorted(set(files.values()))
    print(f"{len(files)} files, {len(sizes)} distinct sizes: "
          f"{', '.join(str(s) for s in sizes)}")

    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        wrapped = {}
        for k, text in masters.items():
            p = tmp / f"{k}.svg"
            p.write_text(full_bleed(text))
            wrapped[k] = p

        rendered = {}
        for px in sizes:
            which = "dock" if px <= SMALL_UP_TO else "full"
            png = tmp / f"{px}.png"
            if not _rasterise(wrapped[which], png, px):
                raise SystemExit(
                    "no SVG rasteriser: set $SVG_RASTERIZER, or "
                    "`pip3 install --user cairosvg`, or install rsvg-convert or "
                    "Chrome. Nothing was written.")
            _flatten(png)
            rendered[px] = (png, which)

        APPICON.mkdir(parents=True, exist_ok=True)
        for name, px in sorted(files.items(), key=lambda kv: kv[1]):
            src, which = rendered[px]
            shutil.copyfile(src, APPICON / name)
            print(f"  {name:<32} {px:>4} px  {which}")

    if verify:
        return check(files)
    return 0


def check(files: dict | None = None) -> int:
    """Re-open every written file and prove what was asked for."""
    from PIL import Image
    files = files or wanted()
    on_disk = {p.name for p in APPICON.glob("*.png")}
    bad = []

    missing = set(files) - on_disk
    extra = on_disk - set(files)
    if missing:
        bad.append(f"missing, but named by Contents.json: {sorted(missing)}")
    if extra:
        bad.append(f"present, but named by nothing: {sorted(extra)}")

    for name, px in sorted(files.items(), key=lambda kv: kv[1]):
        p = APPICON / name
        if not p.exists():
            continue
        im = Image.open(p)
        w, h = im.size
        mode = im.mode
        # Tauri's placeholder is a yellow (#FBC02D-ish) and cyan (#29B6D8-ish)
        # ring on white. Nothing in the Frank mark is saturated except #c8102e,
        # so any strongly saturated non-red pixel is the placeholder.
        rgb = im.convert("RGB")
        raw = rgb.tobytes()                    # not getdata(): deprecated, and slow
        hits = 0
        for i in range(0, len(raw), 3):
            r, g, b = raw[i], raw[i + 1], raw[i + 2]
            if max(r, g, b) - min(r, g, b) < 60:
                continue                       # near-grey: the field or the ink
            if r > g + 40 and r > b + 40:
                continue                       # the mark's own red, #c8102e
            hits += 1
        im.close(); rgb.close()
        ok = (w == px and h == px and mode == "RGB" and hits == 0)
        print(f"  {name:<32} {w}x{h} {mode:<5} placeholder-px={hits}  "
              f"{'ok' if ok else 'FAIL'}")
        if w != px or h != px:
            bad.append(f"{name}: {w}x{h}, Contents.json says {px}x{px}")
        if mode != "RGB":
            bad.append(f"{name}: mode {mode} -- an app icon may not carry alpha")
        if hits:
            bad.append(f"{name}: {hits} saturated non-red pixels -- placeholder?")

    if bad:
        print("\nFAILED:")
        for b in bad:
            print("  -", b)
        return 1
    print(f"\n{len(files)} files, every one square at its Contents.json size, "
          f"RGB with no alpha, no placeholder colour anywhere.")
    return 0


def check_derivation(ttstv: Path) -> int:
    """Prove `full_bleed` is Osca's wrap and not one invented here.

    Apply it to frank-icon.svg and render against the real
    frank-icon-maskable.svg at 1024. Anything but an exact match means the two
    constants above were read wrong, and every icon this writes is subtly off.
    """
    from PIL import Image, ImageChops
    src = (ttstv / "Frank" / "frank-icon.svg").read_text()
    real = ttstv / "Frank" / "frank-icon-maskable.svg"
    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        (tmp / "derived.svg").write_text(full_bleed(src, MASKABLE_SCALE))
        for n, s in (("derived", tmp / "derived.svg"), ("real", real)):
            if not _rasterise(s, tmp / f"{n}.png", 1024):
                raise SystemExit("no SVG rasteriser; nothing proved and nothing written.")
        a = Image.open(tmp / "derived.png").convert("RGB")
        b = Image.open(tmp / "real.png").convert("RGB")
        raw = ImageChops.difference(a, b).tobytes()
        n = sum(1 for i in range(0, len(raw), 3) if raw[i] or raw[i + 1] or raw[i + 2])
        worst = max(raw) if raw else 0
        total = a.size[0] * a.size[1]
    print(f"derivation vs Frank/frank-icon-maskable.svg at 1024: "
          f"{n} of {total} pixels differ ({100.0 * n / total:.4f} %), "
          f"worst channel delta {worst}")
    if n == 0:
        print("EXACT -- the wrap in this file is the maskable master's own.")
        return 0
    if worst <= 2 and n < total * 0.001:
        print("within antialiasing -- the wrap is the maskable master's own.")
        return 0
    print("DIFFERENT -- do not ship this. The two constants have been read wrong.")
    return 1


def check_parity(ttstv: Path) -> int:
    """Prove what this writes IS the mark Osca approved for the Dock.

    The Mac's icons are the reference of record: they were built from the same
    two masters on 1 Sep, installed, and verified chunk-by-chunk with `iconutil`
    (Frank/ICONOGRAPHY.md §7).  Composite one onto the field -- which is the only
    thing this generator does differently -- and it should equal ours exactly.
    Anything above a rasteriser's rounding means the scale or the master is wrong.
    """
    from PIL import Image, ImageChops
    cases = [
        ("desktop/src-tauri/icons/128x128.png", "Frank/frank-icon.svg", 128, "full"),
        ("desktop/src-tauri/icons/32x32.png", "Frank/frank-mark-dock.svg", 32, "dock"),
    ]
    worst_overall, bad = 0, []
    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        for rel, master, px, which in cases:
            mac_png = ttstv / rel
            if not mac_png.is_file():
                print(f"  {rel}: absent -- skipped")
                continue
            svg = tmp / f"{which}.svg"
            svg.write_text(full_bleed((ttstv / master).read_text()))
            out = tmp / f"{which}.png"
            if not _rasterise(svg, out, px):
                raise SystemExit("no SVG rasteriser; nothing proved and nothing written.")
            mac = Image.open(mac_png).convert("RGBA")
            flat = Image.alpha_composite(Image.new("RGBA", mac.size, FIELD), mac).convert("RGB")
            ours = Image.open(out).convert("RGB")
            raw = ImageChops.difference(flat, ours).tobytes()
            n = sum(1 for i in range(0, len(raw), 3) if raw[i] or raw[i + 1] or raw[i + 2])
            worst = max(raw) if raw else 0
            total = px * px
            worst_overall = max(worst_overall, worst)
            print(f"  {rel} on the field vs this at {px}: {n}/{total} px differ "
                  f"({100.0 * n / total:.3f} %), worst channel delta {worst}")
            mac.close(); flat.close(); ours.close()
            if worst > 2:
                bad.append(f"{rel}: worst delta {worst} -- that is not antialiasing")
    if bad:
        print("\nFAILED:")
        for b in bad:
            print("  -", b)
        return 1
    print(f"\nthe iOS icon IS the Mac's approved mark on an opaque field "
          f"(worst channel delta {worst_overall}, i.e. rasteriser rounding).")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--ttstv", type=Path, required=True,
                    help="path to the TTSTV checkout that holds Frank/")
    ap.add_argument("--verify", action="store_true",
                    help="after writing, re-open every file and check it")
    ap.add_argument("--check-derivation", action="store_true",
                    help="prove the full-bleed wrap against the maskable master; write nothing")
    ap.add_argument("--check-parity", action="store_true",
                    help="prove the output is the Mac's approved mark; write nothing")
    ap.add_argument("--check-only", action="store_true",
                    help="check what is already on disk; write nothing")
    a = ap.parse_args(argv)
    root = _ttstv(a.ttstv)
    if a.check_derivation:
        return check_derivation(root)
    if a.check_parity:
        return check_parity(root)
    if a.check_only:
        return check()
    return generate(root, verify=a.verify)


if __name__ == "__main__":
    sys.exit(main())
